version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user-api-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-api-network

  app:
    build: .
    container_name: user-api-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: true
    depends_on:
      - postgres
    networks:
      - user-api-network

volumes:
  postgres_data:

networks:
  user-api-network:
    driver: bridge