spring:
  application:
    name: user-api

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: appuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s

logging:
  level:
    com.example.userapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"